apiVersion: v1
kind: ConfigMap
metadata:
  name: tradebot-env
data:
  name: 'api'
  port: '9001'
  namespace: 'tradebot'
  'rethink.db': 'test'
  'rethink.host': 'localhost'
  'rethink.port': '28015'
  # 'rethink.user': 'test',
  # 'rethink.pass': 'test'
