apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: examplebot
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - examplebot.com
      secretName: examplebot-prod
  rules:
    - host: examplebot.com
      http:
        paths:
          - backend:
              serviceName: examplebot
              servicePort: api
---
apiVersion: v1
kind: Service
metadata:
  name: examplebot
spec:
  type: NodePort
  ports:
    - name: api
      protocol: TCP
      port: 9001
  selector:
    app: examplebot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: examplebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: examplebot
  template:
    metadata:
      labels:
        app: examplebot
    spec:
      containers:
        - name: examplebot
          image: registry.examplebot.com/examplebot
          # ports:
          #   - containerPort: 9001
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: examplebot-env
      imagePullSecrets:
        - name: regcred
